name: Deploy to GitHub Pages



on:

  push: 

    branches: [ main ]



jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "VITE_SUPABASE_ANON_KEY={{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
          echo "VITE_SUPABASE_URL={{ secrets.VITE_SUPABASE_URL }}" >> .env

      - run: npm install

      - run: npm run build

      - uses: peaceiris/actions-gh-pages@v3

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./build

          publish_branch: gh-pages